services:
  db:
    image: postgres:15
    container_name: ellty-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ellty_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ellty-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/ellty_db?schema=public&sslmode=disable"
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: ellty-frontend
    ports:
      - "5173:5173"
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
